// <auto-generated />
using System;
using DBM3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBM3.Migrations
{
    [DbContext(typeof(Milestonee2Context))]
    [Migration("20241214125421_AddFirstNameLastNameToInstructor")]
    partial class AddFirstNameLastNameToInstructor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoursePrerequisite", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<int>("Prereq")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "Prereq")
                        .HasName("PK__CoursePr__F8693C2CB5F87924");

                    b.HasIndex("Prereq");

                    b.ToTable("CoursePrerequisite", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("DBM3.Models.Achievement", b =>
                {
                    b.Property<int>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AchievementID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AchievementId"));

                    b.Property<int?>("BadgeId")
                        .HasColumnType("int")
                        .HasColumnName("BadgeID");

                    b.Property<DateOnly?>("DateEarned")
                        .HasColumnType("date")
                        .HasColumnName("date_earned");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<int?>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("AchievementId")
                        .HasName("PK__Achievem__276330E0101EA2C5");

                    b.HasIndex("BadgeId");

                    b.HasIndex("LearnerId");

                    b.ToTable("Achievement", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.HasKey("AdminId")
                        .HasName("PK__Admin__719FE4E8E0AD72B3");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("Criteria")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("criteria");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<int?>("PassingMarks")
                        .HasColumnType("int")
                        .HasColumnName("passing_marks");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.Property<int?>("TotalMarks")
                        .HasColumnType("int")
                        .HasColumnName("total_marks");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<decimal?>("Weightage")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("weightage");

                    b.HasKey("Id")
                        .HasName("PK__Assessme__3214EC2720651FEC");

                    b.HasIndex("ModuleId", "CourseId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("DBM3.Models.Badge", b =>
                {
                    b.Property<int>("BadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BadgeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BadgeId"));

                    b.Property<string>("Criteria")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("criteria");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<int?>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.HasKey("BadgeId")
                        .HasName("PK__Badge__1918237C2E46D221");

                    b.ToTable("Badge", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.Collaborative", b =>
                {
                    b.Property<int>("QuestId")
                        .HasColumnType("int")
                        .HasColumnName("QuestID");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime")
                        .HasColumnName("deadline");

                    b.Property<int?>("MaxNumParticipants")
                        .HasColumnType("int")
                        .HasColumnName("max_num_participants");

                    b.HasKey("QuestId")
                        .HasName("PK__Collabor__B6619ACBB2F416E0");

                    b.ToTable("Collaborative", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.ContentLibrary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("content_URL");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<string>("Metadata")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("metadata");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PK__ContentL__3214EC277EA15424");

                    b.HasIndex("ModuleId", "CourseId");

                    b.ToTable("ContentLibrary", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int>("CreditPoints")
                        .HasColumnType("int")
                        .HasColumnName("credit_points");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("difficulty_level");

                    b.Property<string>("LearningObjective")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("learning_objective");

                    b.Property<string>("PreRequisites")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("pre_requisites");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CourseId")
                        .HasName("PK__Course__C92D7187C07F22FA");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.CourseEnrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EnrollmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<DateOnly?>("CompletionDate")
                        .HasColumnType("date")
                        .HasColumnName("completion_date");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<DateOnly?>("EnrollmentDate")
                        .HasColumnType("date")
                        .HasColumnName("enrollment_date");

                    b.Property<int?>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("EnrollmentId")
                        .HasName("PK__Course_e__7F6877FBB4305544");

                    b.HasIndex("CourseId");

                    b.HasIndex("LearnerId");

                    b.ToTable("Course_enrollment", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.DiscussionForum", b =>
                {
                    b.Property<int>("ForumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("forumID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ForumId"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastActive")
                        .HasColumnType("datetime")
                        .HasColumnName("last_active");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.HasKey("ForumId")
                        .HasName("PK__Discussi__BBA7A4400A1A8FEF");

                    b.HasIndex("ModuleId", "CourseId");

                    b.ToTable("Discussion_forum", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.EmotionalFeedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FeedbackID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<int?>("ActivityId")
                        .HasColumnType("int")
                        .HasColumnName("activity_ID");

                    b.Property<string>("EmotionalState")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("emotional_state");

                    b.Property<int?>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Emotiona__6A4BEDF655A6F925");

                    b.HasIndex("ActivityId");

                    b.HasIndex("LearnerId");

                    b.ToTable("Emotional_feedback", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.EmotionalfeedbackReview", b =>
                {
                    b.Property<int>("FeedbackId")
                        .HasColumnType("int")
                        .HasColumnName("FeedbackID");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("InstructorID");

                    b.Property<string>("Feedback")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("feedback");

                    b.HasKey("FeedbackId", "InstructorId")
                        .HasName("PK__Emotiona__C39BFD41679364F3");

                    b.HasIndex("InstructorId");

                    b.ToTable("Emotionalfeedback_review", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.FilledSurvey", b =>
                {
                    b.Property<int>("SurveyId")
                        .HasColumnType("int")
                        .HasColumnName("SurveyID");

                    b.Property<string>("Question")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("Answer")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SurveyId", "Question", "LearnerId")
                        .HasName("PK__FilledSu__D89C33C712C200A3");

                    b.HasIndex("LearnerId");

                    b.ToTable("FilledSurvey", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.HealthCondition", b =>
                {
                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("ProfileID");

                    b.Property<string>("Condition")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("condition");

                    b.HasKey("LearnerId", "ProfileId", "Condition")
                        .HasName("PK__HealthCo__930320B0CD9E9CE2");

                    b.ToTable("HealthCondition", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InstructorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("ExpertiseArea")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("expertise_area");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestQualification")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("latest_qualification");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.HasKey("InstructorId")
                        .HasName("PK__Instruct__9D010B7BABDFCD53");

                    b.ToTable("Instructor", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.InteractionLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("ActionType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("action_type");

                    b.Property<int?>("ActivityId")
                        .HasColumnType("int")
                        .HasColumnName("activity_ID");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime");

                    b.HasKey("LogId")
                        .HasName("PK__Interact__5E5499A831449E9E");

                    b.HasIndex("ActivityId");

                    b.HasIndex("LearnerId");

                    b.ToTable("Interaction_log", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.Leaderboard", b =>
                {
                    b.Property<int>("BoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BoardID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoardId"));

                    b.Property<string>("Season")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("season");

                    b.HasKey("BoardId")
                        .HasName("PK__Leaderbo__F9646BD2B26833C9");

                    b.ToTable("Leaderboard", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.Learner", b =>
                {
                    b.Property<int>("LearnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearnerId"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("country");

                    b.Property<string>("CulturalBackground")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cultural_background");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.HasKey("LearnerId")
                        .HasName("PK__Learner__67ABFCFA91637788");

                    b.ToTable("Learner", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.LearnerDiscussion", b =>
                {
                    b.Property<int>("ForumId")
                        .HasColumnType("int")
                        .HasColumnName("ForumID");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("Post")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime")
                        .HasColumnName("time");

                    b.HasKey("ForumId", "LearnerId", "Post")
                        .HasName("PK__LearnerD__FBCECC4A87697A78");

                    b.HasIndex("LearnerId");

                    b.ToTable("LearnerDiscussion", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.LearnersCollaboration", b =>
                {
                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<int>("QuestId")
                        .HasColumnType("int")
                        .HasColumnName("QuestID");

                    b.Property<string>("CompletionStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("completion_status");

                    b.HasKey("LearnerId", "QuestId")
                        .HasName("PK__Learners__CCCDE556AF22C22D");

                    b.HasIndex("QuestId");

                    b.ToTable("LearnersCollaboration", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.LearnersMastery", b =>
                {
                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<int>("QuestId")
                        .HasColumnType("int")
                        .HasColumnName("QuestID");

                    b.Property<string>("CompletionStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("completion_status");

                    b.HasKey("LearnerId", "QuestId")
                        .HasName("PK__Learners__CCCDE556564EA51E");

                    b.HasIndex("QuestId");

                    b.ToTable("LearnersMastery", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.LearningActivity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ActivityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("ActivityType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("activity_type");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("InstructionDetails")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("instruction_details");

                    b.Property<int?>("MaxPoints")
                        .HasColumnType("int")
                        .HasColumnName("Max_points");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.HasKey("ActivityId")
                        .HasName("PK__Learning__45F4A7F187B0FCB4");

                    b.HasIndex("ModuleId", "CourseId");

                    b.ToTable("Learning_activities", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.LearningGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__Learning__3214EC27930D285D");

                    b.ToTable("Learning_goal", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.LearningPath", b =>
                {
                    b.Property<int>("PathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pathID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PathId"));

                    b.Property<string>("AdaptiveRules")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("adaptive_rules");

                    b.Property<string>("CompletionStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("completion_status");

                    b.Property<string>("CustomContent")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("custom_content");

                    b.Property<int?>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("ProfileID");

                    b.HasKey("PathId")
                        .HasName("PK__Learning__BFB8200A23F55F4A");

                    b.HasIndex("LearnerId", "ProfileId");

                    b.ToTable("Learning_path", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.LearningPreference", b =>
                {
                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("Preference")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("preference");

                    b.HasKey("LearnerId", "Preference")
                        .HasName("PK__Learning__6032E1582F004F46");

                    b.ToTable("LearningPreference", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.Module", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("ContentUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ContentURL");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("difficulty");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ModuleId", "CourseId")
                        .HasName("PK__Modules__47E6A09FD4E3F70E");

                    b.HasIndex("CourseId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("DBM3.Models.ModuleContent", b =>
                {
                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("ContentType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Content_type");

                    b.HasKey("ModuleId", "CourseId", "ContentType")
                        .HasName("PK__ModuleCo__C6FAFA2B9412E89E");

                    b.ToTable("ModuleContent", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("message");

                    b.Property<bool?>("ReadStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.Property<string>("UrgencyLevel")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("urgency_level");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3214EC277FB820B2");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.Pathreview", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("InstructorID");

                    b.Property<int>("PathId")
                        .HasColumnType("int")
                        .HasColumnName("PathID");

                    b.Property<string>("Feedback")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("feedback");

                    b.HasKey("InstructorId", "PathId")
                        .HasName("PK__Pathrevi__11D776B874C682FA");

                    b.HasIndex("PathId");

                    b.ToTable("Pathreview", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.PersonalizationProfile", b =>
                {
                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProfileID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<string>("EmotionalState")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("emotional_state");

                    b.Property<string>("PersonalityType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("personality_type");

                    b.Property<string>("PreferredContentType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Preferred_content_type");

                    b.HasKey("LearnerId", "ProfileId")
                        .HasName("PK__Personal__353B3472B382B545");

                    b.ToTable("PersonalizationProfiles");
                });

            modelBuilder.Entity("DBM3.Models.Quest", b =>
                {
                    b.Property<int>("QuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QuestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestId"));

                    b.Property<string>("Criteria")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("criteria");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("difficulty_level");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.HasKey("QuestId")
                        .HasName("PK__Quest__B6619ACB489A81A2");

                    b.ToTable("Quest", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.QuestReward", b =>
                {
                    b.Property<int>("RewardId")
                        .HasColumnType("int")
                        .HasColumnName("RewardID");

                    b.Property<int>("QuestId")
                        .HasColumnType("int")
                        .HasColumnName("QuestID");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<DateTime?>("TimeEarned")
                        .HasColumnType("datetime")
                        .HasColumnName("Time_earned");

                    b.HasKey("RewardId", "QuestId", "LearnerId")
                        .HasName("PK__QuestRew__D251A7C963CB588A");

                    b.HasIndex("LearnerId");

                    b.HasIndex("QuestId");

                    b.ToTable("QuestReward", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.Ranking", b =>
                {
                    b.Property<int>("BoardId")
                        .HasColumnType("int")
                        .HasColumnName("BoardID");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<int?>("Rank")
                        .HasColumnType("int")
                        .HasColumnName("rank");

                    b.Property<int?>("TotalPoints")
                        .HasColumnType("int")
                        .HasColumnName("total_points");

                    b.HasKey("BoardId", "LearnerId")
                        .HasName("PK__Ranking__4F1ED41D06E958F2");

                    b.HasIndex("CourseId");

                    b.HasIndex("LearnerId");

                    b.ToTable("Ranking", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.Reward", b =>
                {
                    b.Property<int>("RewardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RewardID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RewardId"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("value");

                    b.HasKey("RewardId")
                        .HasName("PK__Reward__825015998302920B");

                    b.ToTable("Reward", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.Skill", b =>
                {
                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("Skill1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("skill");

                    b.HasKey("LearnerId", "Skill1")
                        .HasName("PK__Skills__C45BDEA5C7381CD4");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("DBM3.Models.SkillMastery", b =>
                {
                    b.Property<int>("QuestId")
                        .HasColumnType("int")
                        .HasColumnName("QuestID");

                    b.Property<string>("Skill")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("skill");

                    b.HasKey("QuestId", "Skill")
                        .HasName("PK__Skill_Ma__1591B894BEB4AA4B");

                    b.ToTable("Skill_Mastery", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.SkillProgression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("ProficiencyLevel")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("proficiency_level");

                    b.Property<string>("SkillName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("skill_name");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("PK__SkillPro__3214EC2754E05E9C");

                    b.HasIndex("LearnerId", "SkillName");

                    b.ToTable("SkillProgression", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Survey__3214EC2702790C98");

                    b.ToTable("Survey", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.SurveyQuestion", b =>
                {
                    b.Property<int>("SurveyId")
                        .HasColumnType("int")
                        .HasColumnName("SurveyID");

                    b.Property<string>("Question")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("SurveyId", "Question")
                        .HasName("PK__SurveyQu__23FB983B56ADD8BA");

                    b.ToTable("SurveyQuestions");
                });

            modelBuilder.Entity("DBM3.Models.Takenassessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .HasColumnType("int")
                        .HasColumnName("AssessmentID");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<int?>("ScoredPoint")
                        .HasColumnType("int")
                        .HasColumnName("scoredPoint");

                    b.HasKey("AssessmentId", "LearnerId")
                        .HasName("PK__Takenass__8B5147F157A9FCEB");

                    b.HasIndex("LearnerId");

                    b.ToTable("Takenassessment", (string)null);
                });

            modelBuilder.Entity("DBM3.Models.TargetTrait", b =>
                {
                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("Trait")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ModuleId", "CourseId", "Trait")
                        .HasName("PK__Target_t__4E005E4CFB70F715");

                    b.ToTable("Target_traits", (string)null);
                });

            modelBuilder.Entity("LearnersGoal", b =>
                {
                    b.Property<int>("GoalId")
                        .HasColumnType("int")
                        .HasColumnName("GoalID");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.HasKey("GoalId", "LearnerId")
                        .HasName("PK__Learners__3C3540FE0360641F");

                    b.HasIndex("LearnerId");

                    b.ToTable("LearnersGoals", (string)null);
                });

            modelBuilder.Entity("ReceivedNotification", b =>
                {
                    b.Property<int>("NotificationId")
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.HasKey("NotificationId", "LearnerId")
                        .HasName("PK__Received__96B591FD2ADFE8DF");

                    b.HasIndex("LearnerId");

                    b.ToTable("ReceivedNotification", (string)null);
                });

            modelBuilder.Entity("Teach", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("InstructorID");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.HasKey("InstructorId", "CourseId")
                        .HasName("PK__Teaches__F193DC63303A0B43");

                    b.HasIndex("CourseId");

                    b.ToTable("Teaches", (string)null);
                });

            modelBuilder.Entity("CoursePrerequisite", b =>
                {
                    b.HasOne("DBM3.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__CoursePre__Cours__04C58C4B");

                    b.HasOne("DBM3.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("Prereq")
                        .IsRequired()
                        .HasConstraintName("FK__CoursePre__Prere__05B9B084");
                });

            modelBuilder.Entity("DBM3.Models.Achievement", b =>
                {
                    b.HasOne("DBM3.Models.Badge", "Badge")
                        .WithMany("Achievements")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Achieveme__Badge__5A9A4855");

                    b.HasOne("DBM3.Models.Learner", "Learner")
                        .WithMany("Achievements")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Achieveme__Learn__59A6241C");

                    b.Navigation("Badge");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("DBM3.Models.Assessment", b =>
                {
                    b.HasOne("DBM3.Models.Module", "Module")
                        .WithMany("Assessments")
                        .HasForeignKey("ModuleId", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Assessments__1407CFDB");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("DBM3.Models.Collaborative", b =>
                {
                    b.HasOne("DBM3.Models.Quest", "Quest")
                        .WithOne("Collaborative")
                        .HasForeignKey("DBM3.Models.Collaborative", "QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Collabora__Quest__6423B28F");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("DBM3.Models.ContentLibrary", b =>
                {
                    b.HasOne("DBM3.Models.Module", "Module")
                        .WithMany("ContentLibraries")
                        .HasForeignKey("ModuleId", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__ContentLibrary__112B6330");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("DBM3.Models.CourseEnrollment", b =>
                {
                    b.HasOne("DBM3.Models.Course", "Course")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Course_en__Cours__319832C2");

                    b.HasOne("DBM3.Models.Learner", "Learner")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Course_en__Learn__328C56FB");

                    b.Navigation("Course");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("DBM3.Models.DiscussionForum", b =>
                {
                    b.HasOne("DBM3.Models.Module", "Module")
                        .WithMany("DiscussionForums")
                        .HasForeignKey("ModuleId", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Discussion_forum__6EA14102");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("DBM3.Models.EmotionalFeedback", b =>
                {
                    b.HasOne("DBM3.Models.LearningActivity", "Activity")
                        .WithMany("EmotionalFeedbacks")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Emotional__activ__2255EF32");

                    b.HasOne("DBM3.Models.Learner", "Learner")
                        .WithMany("EmotionalFeedbacks")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Emotional__Learn__2161CAF9");

                    b.Navigation("Activity");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("DBM3.Models.EmotionalfeedbackReview", b =>
                {
                    b.HasOne("DBM3.Models.EmotionalFeedback", "FeedbackNavigation")
                        .WithMany("EmotionalfeedbackReviews")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Emotional__Feedb__2DC7A1DE");

                    b.HasOne("DBM3.Models.Instructor", "Instructor")
                        .WithMany("EmotionalfeedbackReviews")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Emotional__Instr__2EBBC617");

                    b.Navigation("FeedbackNavigation");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("DBM3.Models.FilledSurvey", b =>
                {
                    b.HasOne("DBM3.Models.Learner", "Learner")
                        .WithMany("FilledSurveys")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__FilledSur__Learn__4B5804C5");

                    b.HasOne("DBM3.Models.SurveyQuestion", "SurveyQuestion")
                        .WithMany("FilledSurveys")
                        .HasForeignKey("SurveyId", "Question")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__FilledSurvey__4A63E08C");

                    b.Navigation("Learner");

                    b.Navigation("SurveyQuestion");
                });

            modelBuilder.Entity("DBM3.Models.HealthCondition", b =>
                {
                    b.HasOne("DBM3.Models.PersonalizationProfile", "PersonalizationProfile")
                        .WithMany("HealthConditions")
                        .HasForeignKey("LearnerId", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__HealthCondition__0000D72E");

                    b.Navigation("PersonalizationProfile");
                });

            modelBuilder.Entity("DBM3.Models.InteractionLog", b =>
                {
                    b.HasOne("DBM3.Models.LearningActivity", "Activity")
                        .WithMany("InteractionLogs")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Interacti__activ__1D913A15");

                    b.HasOne("DBM3.Models.Learner", "Learner")
                        .WithMany("InteractionLogs")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Interacti__Learn__1E855E4E");

                    b.Navigation("Activity");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("DBM3.Models.LearnerDiscussion", b =>
                {
                    b.HasOne("DBM3.Models.DiscussionForum", "Forum")
                        .WithMany("LearnerDiscussions")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnerDi__Forum__717DADAD");

                    b.HasOne("DBM3.Models.Learner", "Learner")
                        .WithMany("LearnerDiscussions")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnerDi__Learn__7271D1E6");

                    b.Navigation("Forum");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("DBM3.Models.LearnersCollaboration", b =>
                {
                    b.HasOne("DBM3.Models.Learner", "Learner")
                        .WithMany("LearnersCollaborations")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnersC__Learn__67001F3A");

                    b.HasOne("DBM3.Models.Collaborative", "Quest")
                        .WithMany("LearnersCollaborations")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnersC__Quest__67F44373");

                    b.Navigation("Learner");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("DBM3.Models.LearnersMastery", b =>
                {
                    b.HasOne("DBM3.Models.Learner", "Learner")
                        .WithMany("LearnersMasteries")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnersM__Learn__6AD0B01E");

                    b.HasOne("DBM3.Models.Quest", "Quest")
                        .WithMany("LearnersMasteries")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnersM__Quest__6BC4D457");

                    b.Navigation("Learner");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("DBM3.Models.LearningActivity", b =>
                {
                    b.HasOne("DBM3.Models.Module", "Module")
                        .WithMany("LearningActivities")
                        .HasForeignKey("ModuleId", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Learning_activit__1AB4CD6A");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("DBM3.Models.LearningPath", b =>
                {
                    b.HasOne("DBM3.Models.PersonalizationProfile", "PersonalizationProfile")
                        .WithMany("LearningPaths")
                        .HasForeignKey("LearnerId", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Learning_path__25325BDD");

                    b.Navigation("PersonalizationProfile");
                });

            modelBuilder.Entity("DBM3.Models.LearningPreference", b =>
                {
                    b.HasOne("DBM3.Models.Learner", "Learner")
                        .WithMany("LearningPreferences")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearningP__Learn__7A47FDD8");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("DBM3.Models.Module", b =>
                {
                    b.HasOne("DBM3.Models.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Modules__CourseI__08961D2F");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DBM3.Models.ModuleContent", b =>
                {
                    b.HasOne("DBM3.Models.Module", "Module")
                        .WithMany("ModuleContents")
                        .HasForeignKey("ModuleId", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ModuleContent__0E4EF685");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("DBM3.Models.Pathreview", b =>
                {
                    b.HasOne("DBM3.Models.Instructor", "Instructor")
                        .WithMany("Pathreviews")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Pathrevie__Instr__29F710FA");

                    b.HasOne("DBM3.Models.LearningPath", "Path")
                        .WithMany("Pathreviews")
                        .HasForeignKey("PathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Pathrevie__PathI__2AEB3533");

                    b.Navigation("Instructor");

                    b.Navigation("Path");
                });

            modelBuilder.Entity("DBM3.Models.PersonalizationProfile", b =>
                {
                    b.HasOne("DBM3.Models.Learner", "Learner")
                        .WithMany("PersonalizationProfiles")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Personali__Learn__7D246A83");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("DBM3.Models.QuestReward", b =>
                {
                    b.HasOne("DBM3.Models.Learner", "Learner")
                        .WithMany("QuestRewards")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__QuestRewa__Learn__77368703");

                    b.HasOne("DBM3.Models.Quest", "Quest")
                        .WithMany("QuestRewards")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__QuestRewa__Quest__764262CA");

                    b.HasOne("DBM3.Models.Reward", "Reward")
                        .WithMany("QuestRewards")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__QuestRewa__Rewar__754E3E91");

                    b.Navigation("Learner");

                    b.Navigation("Quest");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("DBM3.Models.Ranking", b =>
                {
                    b.HasOne("DBM3.Models.Leaderboard", "Board")
                        .WithMany("Rankings")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Ranking__BoardID__3B219CFC");

                    b.HasOne("DBM3.Models.Course", "Course")
                        .WithMany("Rankings")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Ranking__CourseI__3D09E56E");

                    b.HasOne("DBM3.Models.Learner", "Learner")
                        .WithMany("Rankings")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Ranking__Learner__3C15C135");

                    b.Navigation("Board");

                    b.Navigation("Course");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("DBM3.Models.Skill", b =>
                {
                    b.HasOne("DBM3.Models.Learner", "Learner")
                        .WithMany("Skills")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Skills__LearnerI__776B912D");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("DBM3.Models.SkillMastery", b =>
                {
                    b.HasOne("DBM3.Models.Quest", "Quest")
                        .WithMany("SkillMasteries")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Skill_Mas__Quest__614745E4");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("DBM3.Models.SkillProgression", b =>
                {
                    b.HasOne("DBM3.Models.Skill", "Skill")
                        .WithMany("SkillProgressions")
                        .HasForeignKey("LearnerId", "SkillName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__SkillProgression__56C9B771");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("DBM3.Models.SurveyQuestion", b =>
                {
                    b.HasOne("DBM3.Models.Survey", "Survey")
                        .WithMany("SurveyQuestions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SurveyQue__Surve__478773E1");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("DBM3.Models.Takenassessment", b =>
                {
                    b.HasOne("DBM3.Models.Assessment", "Assessment")
                        .WithMany("Takenassessments")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Takenasse__Asses__16E43C86");

                    b.HasOne("DBM3.Models.Learner", "Learner")
                        .WithMany("Takenassessments")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Takenasse__Learn__17D860BF");

                    b.Navigation("Assessment");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("DBM3.Models.TargetTrait", b =>
                {
                    b.HasOne("DBM3.Models.Module", "Module")
                        .WithMany("TargetTraits")
                        .HasForeignKey("ModuleId", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Target_traits__0B7289DA");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("LearnersGoal", b =>
                {
                    b.HasOne("DBM3.Models.LearningGoal", null)
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnersG__GoalI__41CE9A8B");

                    b.HasOne("DBM3.Models.Learner", null)
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnersG__Learn__42C2BEC4");
                });

            modelBuilder.Entity("ReceivedNotification", b =>
                {
                    b.HasOne("DBM3.Models.Learner", null)
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ReceivedN__Learn__52050254");

                    b.HasOne("DBM3.Models.Notification", null)
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ReceivedN__Notif__5110DE1B");
                });

            modelBuilder.Entity("Teach", b =>
                {
                    b.HasOne("DBM3.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Teaches__CourseI__365CE7DF");

                    b.HasOne("DBM3.Models.Instructor", null)
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Teaches__Instruc__3568C3A6");
                });

            modelBuilder.Entity("DBM3.Models.Assessment", b =>
                {
                    b.Navigation("Takenassessments");
                });

            modelBuilder.Entity("DBM3.Models.Badge", b =>
                {
                    b.Navigation("Achievements");
                });

            modelBuilder.Entity("DBM3.Models.Collaborative", b =>
                {
                    b.Navigation("LearnersCollaborations");
                });

            modelBuilder.Entity("DBM3.Models.Course", b =>
                {
                    b.Navigation("CourseEnrollments");

                    b.Navigation("Modules");

                    b.Navigation("Rankings");
                });

            modelBuilder.Entity("DBM3.Models.DiscussionForum", b =>
                {
                    b.Navigation("LearnerDiscussions");
                });

            modelBuilder.Entity("DBM3.Models.EmotionalFeedback", b =>
                {
                    b.Navigation("EmotionalfeedbackReviews");
                });

            modelBuilder.Entity("DBM3.Models.Instructor", b =>
                {
                    b.Navigation("EmotionalfeedbackReviews");

                    b.Navigation("Pathreviews");
                });

            modelBuilder.Entity("DBM3.Models.Leaderboard", b =>
                {
                    b.Navigation("Rankings");
                });

            modelBuilder.Entity("DBM3.Models.Learner", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("CourseEnrollments");

                    b.Navigation("EmotionalFeedbacks");

                    b.Navigation("FilledSurveys");

                    b.Navigation("InteractionLogs");

                    b.Navigation("LearnerDiscussions");

                    b.Navigation("LearnersCollaborations");

                    b.Navigation("LearnersMasteries");

                    b.Navigation("LearningPreferences");

                    b.Navigation("PersonalizationProfiles");

                    b.Navigation("QuestRewards");

                    b.Navigation("Rankings");

                    b.Navigation("Skills");

                    b.Navigation("Takenassessments");
                });

            modelBuilder.Entity("DBM3.Models.LearningActivity", b =>
                {
                    b.Navigation("EmotionalFeedbacks");

                    b.Navigation("InteractionLogs");
                });

            modelBuilder.Entity("DBM3.Models.LearningPath", b =>
                {
                    b.Navigation("Pathreviews");
                });

            modelBuilder.Entity("DBM3.Models.Module", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("ContentLibraries");

                    b.Navigation("DiscussionForums");

                    b.Navigation("LearningActivities");

                    b.Navigation("ModuleContents");

                    b.Navigation("TargetTraits");
                });

            modelBuilder.Entity("DBM3.Models.PersonalizationProfile", b =>
                {
                    b.Navigation("HealthConditions");

                    b.Navigation("LearningPaths");
                });

            modelBuilder.Entity("DBM3.Models.Quest", b =>
                {
                    b.Navigation("Collaborative");

                    b.Navigation("LearnersMasteries");

                    b.Navigation("QuestRewards");

                    b.Navigation("SkillMasteries");
                });

            modelBuilder.Entity("DBM3.Models.Reward", b =>
                {
                    b.Navigation("QuestRewards");
                });

            modelBuilder.Entity("DBM3.Models.Skill", b =>
                {
                    b.Navigation("SkillProgressions");
                });

            modelBuilder.Entity("DBM3.Models.Survey", b =>
                {
                    b.Navigation("SurveyQuestions");
                });

            modelBuilder.Entity("DBM3.Models.SurveyQuestion", b =>
                {
                    b.Navigation("FilledSurveys");
                });
#pragma warning restore 612, 618
        }
    }
}
